{{/*
Copyright 2026 kropath Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{/*
The configRef every emitted <Family>Config carries as its resource-name label, and that
resource instances in this namespace resolve against (ADR-015 §5.8.5, rgd-patterns §1).
*/}}
{{- define "tenant-namespace-onboarding.configRef" -}}
{{- .Values.configRef | default "general-policy" -}}
{{- end -}}

{{/*
Raw YAML text of onboarding/tenant-namespace/family-kind-map.yaml (generated by
hack/gen-family-kind-map.sh from crds/*config.yaml — the source of truth for which
<Family>Config Kind a family slug maps to). Callers must pipe the result through `fromYaml`
themselves — `include` always returns a string, so parsing here would hand callers a Go
map's default string representation instead of the map itself.
*/}}
{{- define "tenant-namespace-onboarding.familyKindMapYAML" -}}
{{- .Files.Get "family-kind-map.yaml" -}}
{{- end -}}
