#!/usr/bin/env bash
# Copyright 2026 kropath Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -euo pipefail

CLUSTER_NAME="${CLUSTER_NAME:-kropath-aws-test}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if kind get clusters | grep -q "^${CLUSTER_NAME}$"; then
  echo "Kind cluster '${CLUSTER_NAME}' already exists — skipping creation."
else
  echo "Creating Kind cluster: ${CLUSTER_NAME}..."
  kind create cluster --name "${CLUSTER_NAME}" --config "${SCRIPT_DIR}/fixtures/kind-config.yaml"
fi

kubectl config use-context "kind-${CLUSTER_NAME}"

if kubectl get ns kro-system &>/dev/null; then
  echo "Namespace 'kro-system' already exists — skipping kro operator installation."
else
  echo "Creating namespace 'kro-system'..."
  kubectl create namespace kro-system
fi

echo "==> Installing kro operator (v0.9.2)..."
kubectl apply -f https://github.com/kubernetes-sigs/kro/releases/download/v0.9.2/kro-core-install-manifests.yaml

kubectl apply -f "${SCRIPT_DIR}/fixtures/rbac/kro-controller.yaml"
kubectl rollout status deployment/kro -n kro-system --timeout=120s

echo "==> Installing ACK CRD definitions..."
source "${SCRIPT_DIR}/../hack/install-provider-crds.sh"

echo "==> Installing kropath CRD definitions..."
kubectl apply -f "${SCRIPT_DIR}/../crds/*.yaml"
kubectl apply -f "${SCRIPT_DIR}/../crds/policy/awspolicydocument.yaml"

echo "==> Installing kropath.run RGDS definitions..."
kubectl apply -f "${SCRIPT_DIR}/../rgds/*.yaml"

# x-kubernetes-validations (immutability, mutual exclusivity) cannot be auto-generated by kro;
# wait for kro to create and establish the CRD from the RGD schema, then patch them in.
# kro creates the CRD asynchronously, so poll until it appears before running kubectl wait.
echo "==> Waiting for kro to create awskmskeys.kropath.run CRD..."
for i in $(seq 1 60); do
  kubectl get crd awskmskeys.kropath.run &>/dev/null && break
  sleep 2
done
echo "==> Waiting for awskmskeys.kropath.run CRD to be Established..."
kubectl wait crd awskmskeys.kropath.run --for=condition=Established --timeout=120s

echo "==> Patching x-kubernetes-validations onto AWSKMSKey CRD..."
kubectl patch crd awskmskeys.kropath.run --type=json -p '[
  {"op":"add","path":"/spec/versions/0/schema/openAPIV3Schema/x-kubernetes-validations","value":[
    {"rule":"self.spec.keySpec == \"\" || !has(oldSelf.spec) || oldSelf.spec.keySpec == \"\" || self.spec.keySpec == oldSelf.spec.keySpec","message":"keySpec is immutable after creation"},
    {"rule":"self.spec.keyUsage == \"\" || !has(oldSelf.spec) || oldSelf.spec.keyUsage == \"\" || self.spec.keyUsage == oldSelf.spec.keyUsage","message":"keyUsage is immutable after creation"},
    {"rule":"!(self.spec.policy != \"\" && self.spec.keyPolicyRef != \"\")","message":"policy and keyPolicyRef are mutually exclusive"}
  ]}
]'

echo "==> Test environment ready."
