#!/usr/bin/env bash
# Copyright 2026 kropath Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Fail if any YAML under crds/ defines a resource-kind CRD.
# Resource-kind CRDs (e.g. awsiamroles.kropath.run) are auto-generated by kro
# and must not be hand-authored under crds/.
#
# Allowed CRD names end in:
#   *configs.kropath.run        — governance ResourceConfig CRDs
#   awspolicydocuments.kropath.run — approved utility CRD

set -euo pipefail

ALLOWED_PATTERNS="configs\.kropath\.run$|awspolicydocuments\.kropath\.run$"

# Collect all YAML files under crds/ that declare a CustomResourceDefinition.
# grep returns exit 1 when no files match; || true keeps set -e from aborting.
mapfile -t CRD_FILES < <(find crds/ -name '*.yaml' \
  -exec grep -l 'kind: CustomResourceDefinition' {} + 2>/dev/null || true)

if [[ ${#CRD_FILES[@]} -eq 0 ]]; then
  echo "OK: no CRD files found under crds/"
  exit 0
fi

FAILED=0
for f in "${CRD_FILES[@]}"; do
  NAME=$(grep 'name:' "$f" | head -1 | awk '{print $2}')
  if ! echo "$NAME" | grep -qE "$ALLOWED_PATTERNS"; then
    echo "FAIL: $f defines resource-kind CRD '$NAME' — resource-kind CRDs are auto-generated by kro, not hand-authored"
    FAILED=1
  fi
done

if [[ $FAILED -eq 1 ]]; then
  exit 1
fi

echo "OK: all CRDs under crds/ are governance or approved utility CRDs"
