#!/usr/bin/env bash
# Copyright 2026 kropath Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Regenerates onboarding/tenant-namespace/family-kind-map.yaml from crds/*config.yaml.
#
# The tenant-namespace onboarding chart (KRO-1140) takes a bare family slug (e.g. "s3") and
# must emit the matching <Family>Config Kind (e.g. "S3Config"). Kind names do not follow a
# mechanical PascalCase(slug) rule (DynamoDBConfig, not DynamodbConfig), so the mapping is
# generated from the CRD source of truth rather than hand-maintained — this script is what
# `make onboarding-lint` re-runs to detect drift when a new family's CRD is added.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

out="onboarding/tenant-namespace/family-kind-map.yaml"

{
  echo "# Generated by hack/gen-family-kind-map.sh — DO NOT EDIT BY HAND."
  echo "# Regenerate with: hack/gen-family-kind-map.sh"
  echo "# Maps a tenant-facing family slug (onboarding values.yaml 'families' entry) to the"
  echo "# <Family>Config Kind that ships in crds/. Excludes kropathconfig.yaml — KropathConfig"
  echo "# is the org-wide singleton, not a per-family resource config (ADR-015 §5.7)."
} > "$out"

for file in crds/*config.yaml; do
  base=$(basename "$file" .yaml)
  slug=${base%config}
  if [ "$slug" = "kropath" ]; then
    continue
  fi
  kind=$(awk '/^  names:/{flag=1} flag && /kind:/{print $2; exit}' "$file")
  if [ -z "$kind" ]; then
    echo "gen-family-kind-map.sh: no kind found in $file" >&2
    exit 1
  fi
  echo "${slug}: ${kind}"
done | sort >> "$out"

echo "Wrote $out"
