# Copyright 2026 kropath Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: aws.kropath.run/v1alpha1
kind: ACMConfig
metadata:
  name: internal-services
  namespace: kro-system
  labels:
    aws.kropath.run/resource-name: internal-services
spec:
  mandatory:
    keyAlgorithm: ""
    certificateTransparencyLogging: ""
    usageMode: ""
    keyStorageSecurityStandard: ""
    tags: {}
    syncedLabels: {}
    syncedAnnotations: {}
  defaults:
    keyAlgorithm: "EC_prime256v1"
    certificateTransparencyLogging: "DISABLED"
    usageMode: "SHORT_LIVED_CERTIFICATE"
    keyStorageSecurityStandard: ""
    tags: {}
    syncedLabels: {}
    syncedAnnotations: {}
